### ISSUE TITLE
Update to go 1.17

### ISSUE THREAD

**Issue by tjdevries** [sourcegraph/lsif-go#192]

**Comment by varungandhi-src** [comment]
I didn't realize there was a ticket for bumping the version.

Reposting the information from Slack: Previously, I bumped it in https://github.com/sourcegraph/lsif-go/pull/215, it was later reverted: https://github.com/sourcegraph/lsif-go/pull/217 because of an error: https://github.com/sourcegraph/sourcegraph/runs/4169610043?check_suite_focus=true

**Comment by varungandhi-src** [comment]
Slack thread where a customer would benefit from us bumping the Go version: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1636991084455200, so they can use the Docker image directly instead of using a binary.

**Comment by varungandhi-src** [comment]
Fixed in https://github.com/sourcegraph/lsif-go/pull/235
